name: Build and Publish to APT

on:
  push:
    branches:
    - release/**
    - rc/8.0

jobs:
  build-source-package:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        dist: ${{ fromJSON(vars.BUILD_DISTS) }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
          sudo apt-get update && \
          sudo apt-get install \
           debhelper dput tcl-tls libsystemd-dev pkgconf cmake clang libssl-dev python3-pip python3-venv python3-dev unzip rsync git wget tcl curl build-essential gcc-11 g++-11
    - name: Determine version
      run: |
          VERSION=$(head -1 debian/changelog | sed 's/^.*([0-9]*:*\([0-9.]*\)-.*$/\1/')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
    - name: Get source tarball
      run: |
          curl --silent -L "https://github.com/redis/redis/archive/refs/tags/8.0-m01.tar.gz" -o redis_${VERSION}.orig.tar.gz
    - name: Build source package
      run: |
        mkdir -p redis-${VERSION}
        tar --extract --gunzip --file redis_${VERSION}.orig.tar.gz --strip-components=1 -C redis-${VERSION}  
        sed -i 's/INSTALL_BIN=\$(PREFIX)\/bin/INSTALL_BIN=\$(DESTDIR)\$(PREFIX)\/bin/' redis-${VERSION}/src/Makefile
        cp -pr debian redis-${VERSION}
        sed -i "s/@RELEASE@/${{ matrix.dist }}/g" redis-${VERSION}/debian/changelog
        ( cd redis-${VERSION} && dpkg-buildpackage -S )
    - name: Upload source package artifact
      uses: actions/upload-artifact@v4
      with:
        name: source-${{ matrix.dist }}
        path: |
          redis_*.tar.xz
          redis_*.dsc
          redis_*.orig.tar.gz

  build-binary-package:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        dist: ${{ fromJSON(vars.BUILD_DISTS) }}
        arch: ${{ fromJSON(vars.BUILD_ARCHS) }}
        exclude: ${{ fromJSON(vars.BUILD_EXCLUDE) }}
    needs: build-source-package
    steps:
    - uses: actions/checkout@v4
    - name: Determine build architecture
      run: |
          if [ ${{ matrix.arch }} = "i386" ]; then
              BUILD_ARCH=i386
          else
              BUILD_ARCH=amd64
          fi
          echo "BUILD_ARCH=${BUILD_ARCH}" >> $GITHUB_ENV
    - name: Setup APT Signing key
      run: |
          mkdir -m 0700 -p ~/.gnupg
          echo "$APT_SIGNING_KEY" | gpg --import
      env:
        APT_SIGNING_KEY: ${{ secrets.APT_SIGNING_KEY }}
    - name: Install dependencies
      run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            sbuild debhelper \
            wget make cmake clang-format gcc python3 python3-venv python3-pip lcov git openssl libssl-dev unzip rsync build-essential gcc-11 g++-11 pkg-config
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 60 --slave /usr/bin/g++ g++ /usr/bin/g++-11
          sudo sbuild-adduser $USER
    - name: Prepare sbuild environment
      run: sudo ./setup_sbuild.sh ${{ matrix.dist }} ${{ env.BUILD_ARCH }}
    - name: Get source package
      uses: actions/download-artifact@v4
      with:
        name: source-${{ matrix.dist }}
    - name: Build binary package
      run: |
          sudo sbuild \
            --chroot-setup-commands "apt-get update && apt-get install -y python3-pip systemd" \
            --nolog \
            --no-run-lintian \
            --host ${{ matrix.arch }} \
            --build ${{ env.BUILD_ARCH }} \
            --dist ${{ matrix.dist }} *.dsc
    - name: Upload binary package artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.dist }}-${{ matrix.arch }}
        path: |
          *.deb

  smoke-test-packages:
    runs-on: ubuntu-latest
    needs: build-binary-package
    env:
      ARCH: amd64
    strategy:
      matrix:
        image: ${{ fromJSON(vars.SMOKE_TEST_IMAGES) }}
    container: ${{ matrix.image }}
    steps:
    - name: Get binary packages
      uses: actions/download-artifact@v4
    - name: Install packages
      run: |
        apt-get update
        cd binary-$(echo ${{ matrix.image }} | cut -d: -f2)-${{ env.ARCH }} && apt install --yes ./*.deb
    - name: Run redis-server smoke test
      run: |
        /usr/bin/redis-server /etc/redis/redis.conf
        sleep 3
        redis-benchmark -P 10
    - name: Run redis-sentinel smoke test
      run: |
        /usr/bin/redis-sentinel /etc/redis/sentinel.conf
        sleep 3
        echo ping | redis-cli -p 26379

  upload-packages:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: smoke-test-packages
    steps:
    - name: Setup APT Signing key
      env:
        APT_SIGNING_KEY: ${{ secrets.APT_SIGNING_KEY }}  
      run: |
        mkdir -m 0700 -p ~/.gnupg
        echo "$APT_SIGNING_KEY" | gpg --import
    - name: Get binary packages
      uses: actions/download-artifact@v4
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.7"
    - name: Install deb-s3
      env:
        DEB_S3_VERSION: "0.11.3"
      run: |
          curl -sLO https://github.com/deb-s3/deb-s3/releases/download/${{ env.DEB_S3_VERSION }}/deb-s3-${{ env.DEB_S3_VERSION }}.gem
          gem install deb-s3-${{ env.DEB_S3_VERSION }}.gem
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.APT_S3_REGION }}
        role-to-assume: ${{ secrets.APT_S3_IAM_ARN }}
    - name: Upload packages
      env:
        APT_S3_BUCKET: ${{ secrets.APT_S3_BUCKET }}
        APT_S3_REGION: ${{ secrets.APT_S3_REGION }}
      run: |
        # Quick hack to deal with duplicate _all packages
        rm -f binary-*-i386/*_all.deb
        for dir in binary-*; do \
            dist=$(echo $dir | cut -d- -f 2) ; \
            deb-s3 upload \
                --bucket ${{ env.APT_S3_BUCKET }} \
                --s3-region ${{ env.APT_S3_REGION }} \
                --codename $dist \
                --suite $dist \
                --origin packages.redis.io \
                --preserve-versions \
                --lock \
                --fail-if-exists \
                --sign \
                --prefix deb \
                $dir/*.deb ; \
        done

